version: "3"
# 创建mysql和gitea专用网络
networks:
  gitea:
    external: false
services:
  server:
    # 指定gitea镜像及版本
    image: gitea/gitea
    # 指定容器别名
    container_name: gitea
    # 配置容器环境
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=mysql
      - DB_HOST=db:3306
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=gitea
    # 开机自启
    restart: always
    # 指定容器使用的网络
    networks:
      - gitea
    # 配置挂载卷
    volumes:
      - /data:/data:rw
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    # 配置端口映射
    ports:
      - "3000:3000"
      - "222:22"
    # 指定依赖(先安装依赖)
    depends_on:
      - db
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
    networks:
      - gitea
    volumes:
      - /data/mysql:/var/lib/mysql:rw